- customization/jitsi-resources/beratungCustom/static/js/script.js
> fix: e2ee custom event

- customization/jitsi-resources/web/custom-config.js
> feat: enabled encoded transform support for safari

- customization/jitsi-resources/prosody/customplugins/mod_close_room.lua
> fix: statistics

- customization/jitsi-resources/web/custom-config.js
> fix: remove subject from lobby

- templates/migration/Chart.yaml
- templates/migration/templates/deployment.yaml
- templates/migration/templates/env-configmap.yaml
- templates/migration/templates/secret.yaml
- templates/migration/values.yaml
> Migration tool

- charts/mariadb/templates/mariadb-env-configmap.yaml
- templates/migration/templates/migrationservice-secret.yaml
- values.yaml
> Vic 2265 add new mongo migration

- templates/migration/templates/migrationservice-deployment.yaml
> chore: add secret for migrationservice

- customization/keycloak-resources/custom-theme/login/messages/messages_en.properties
> fix: mail message

- customization/keycloak-resources/custom-theme/login/messages/messages_en.properties
> fix: change english mail verify message

- templates/uploadservice/uploadservice-ingress.yaml
> feat: raised max body size because of e2ee attachments

- templates/counselingtoolsservice/counselingtoolsservice-deployment.yaml
- templates/counselingtoolsservice/counselingtoolsservice-env-configmap.yaml
> New env. variable for counseling tools service

- templates/uploadservice/uploadservice-ingress.yaml
> feat: raised proxy body size to 25MB

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-secret.yaml
> feat: added rocket mongo url for userservice

- charts/videobackend/values.yaml
- customization/jitsi-resources/web/custom-config.js
> Obi jitsi update and features

- charts/budibase/templates/budibase-vi-proxy-service.yaml
> condition on budibase proxy service

- templates/counselingtoolsservice/counselingtoolsservice-env-configmap.yaml
> added new env. variable

- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/statisticsservice/statisticsservice-env-configmap.yaml
> chore: cons type api url added to stats service

- templates/migration/templates/migrationservice-configmap.yaml
- templates/migration/templates/migrationservice-deployment.yaml
- templates/migration/templates/migrationservice-secret.yaml
> chore: add needed env variables for migration tool extension

- templates/agencyservice/agencyservice-deployment.yaml
- templates/agencyservice/agencyservice-env-configmap.yaml
- values.yaml
> fix: enable cron expression to delete agencies marked for deletion

- charts/budibase/templates/budibase-vi-proxy-service.yaml
> update of proxy service config

- charts/budibase/templates/budibase-vi-proxy-service.yaml
> fix: helm chart service definition

- consulting-type-settings/0-beratung.json
removed the locked agencies attribute from json
> removed the locked agencies attribute

- charts/budibase/templates/budibase-ingress.yaml
> fix: budibase proxy ingress

- charts/budibase/templates/budibase-ingress.yaml
Reverts Onlineberatung/onlineBeratung-kubernetes#42
> Revert "budibase proxy ingress change for /api/self and /api/global/config"

- templates/documentationservice/documentationservice-deployment.yaml
- templates/documentationservice/documentationservice-env-configmap.yaml
- templates/documentationservice/documentationservice-ingress.yaml
- templates/documentationservice/documentationservice-service.yaml
- values.yaml
> feat: add documentation service

- templates/counselingtoolsservice/counselingtoolsservice-deployment.yaml
- templates/counselingtoolsservice/counselingtoolsservice-env-configmap.yaml
> fix: env app fix

- templates/agencyservice/agencyservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/liveservice/liveservice-deployment.yaml
- templates/mailservice/mailservice-deployment.yaml
- templates/messageservice/messageservice-deployment.yaml
- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/userservice/userservice-deployment.yaml
- templates/videoservice/videoservice-deployment.yaml
> Ob 4497 add http probes

- templates/agencyservice/agencyservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/liveservice/liveservice-deployment.yaml
- templates/mailservice/mailservice-deployment.yaml
- templates/messageservice/messageservice-deployment.yaml
- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/userservice/userservice-deployment.yaml
- templates/videoservice/videoservice-deployment.yaml
Reverts Onlineberatung/onlineBeratung-kubernetes#50
> Revert "Ob 4497 add http probes"

- charts/mariadb/templates/mariadb-env-configmap.yaml
- templates/videoservice/videoservice-deployment.yaml
- templates/videoservice/videoservice-env-configmap.yaml
- templates/videoservice/videoservice-secret.yaml
- values.yaml
> Ob 1807 add datasource for videoservice

- charts/videobackend/templates/prosody/prosody-deployment.yaml
- charts/videobackend/templates/prosody/prosody-videoservice-config-configmap.yaml
- customization/jitsi-resources/prosody/customplugins/mod_close_room.lua
> Ob 4923 prep lua script to call videoservice api

- charts/mongodb/templates/mongodb-statefulset.yaml
- charts/videobackend/templates/prosody/prosody-videoservice-config-configmap.yaml
- charts/videobackend/values.yaml
> fix: prosody videoservice config

- templates/videoservice/videoservice-env-configmap.yaml
> feat: fix for videoservice config map

- charts/videobackend/templates/prosody/prosody-videoservice-config-configmap.yaml
> feat: fix videoservice config map

- templates/consultingtypeservice/consultingtypeservice-ingress.yaml
- templates/migration/templates/migrationservice-configmap.yaml
- templates/migration/templates/migrationservice-deployment.yaml
- templates/migration/templates/migrationservice-secret.yaml
> chore: added more datasources to migrationservice

- templates/migration/templates/migrationservice-configmap.yaml
- templates/migration/templates/migrationservice-deployment.yaml
- templates/migration/templates/migrationservice-secret.yaml
> feat: add new env variables for consultingtypeservice to migration tool

- templates/mailservice/mailservice-deployment.yaml
- templates/mailservice/mailservice-env-configmap.yaml
> feat: added props for mailservice config

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
- values.yaml
> feat: added ability to raise hikari pool size

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
- values.yaml
> feat: add config for appointment deletion service

- charts/mongodb/templates/mongodb-statefulset.yaml
> feat: added ability to set max_map_count for mongodb

- charts/keycloak/templates/keycloak-deployment.yaml
- charts/mariadb/templates/mariadb-deployment.yaml
- charts/mongodb/templates/mongodb-statefulset.yaml
- charts/openldap/templates/openldap-deployment.yaml
- charts/rabbitmq/templates/rabbitmq-deployment.yaml
- charts/rocketchat/templates/rocketchat-deployment.yaml
- charts/videobackend/templates/jicofo/jicofo-deployment.yaml
- charts/videobackend/templates/jvb/jvb-deployment.yaml
- charts/videobackend/templates/prosody/prosody-deployment.yaml
- charts/videobackend/templates/web/web-deployment.yaml
- templates/adminconsole/adminconsole-deployment.yaml
- templates/agencyservice/agencyservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/counselingtoolsservice/counselingtoolsservice-deployment.yaml
- templates/documentationservice/documentationservice-deployment.yaml
- templates/frontend/frontend-deployment.yaml
- templates/liveservice/liveservice-deployment.yaml
- templates/mailservice/mailservice-deployment.yaml
- templates/messageservice/messageservice-deployment.yaml
- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/userservice/userservice-deployment.yaml
- templates/videoservice/videoservice-deployment.yaml
- values.yaml
> feat: added ability to limit resources for all pods

- templates/migration/templates/migrationservice-configmap.yaml
- values.yaml
> fix: add possibility to create jitsi technical user

- charts/budibase/templates/budibase-ingress.yaml
> fix: add allow from response header in budibase ingress

- Chart.lock
- Chart.yaml
- values.yaml
> feat: weblate

- templates/mailservice/mailservice-env-configmap.yaml
- templates/migration/templates/migrationservice-configmap.yaml
- values.yaml
> chore: fix k8s variables

- templates/mailservice/mailservice-settings-cache-configmap.yaml
> chore: remove invalid config map

- templates/migration/templates/migrationservice-deployment.yaml
- templates/migration/templates/migrationservice-secret.yaml
> chore: migration fixing the inconsistent rc_user_id in rocketchat

- templates/frontend/frontend-deployment.yaml
- templates/frontend/frontend-env-configmap.yaml
- templates/frontend/frontend-secret.yaml
- templates/frontend/frontend-service.yaml
- values.yaml
> feat: prepare for node frontend and weblate integration

- templates/frontend/frontend-deployment.yaml
> Ob weblate frontend

- templates/frontend/frontend-service.yaml
> fix: fixed integer port

- templates/mailservice/mailservice-env-configmap.yaml
- templates/migration/templates/migrationservice-configmap.yaml
- templates/migration/templates/migrationservice-deployment.yaml
- values.yaml
> Tsystems 101

- templates/migration/templates/migrationservice-deployment.yaml
> chore: deployment

- charts/budibase/templates/budibase-ingress.yaml
- templates/mailservice/mailservice-env-configmap.yaml
> Ob fix path

- templates/counselingtoolsservice/counselingtoolsservice-deployment.yaml
- templates/counselingtoolsservice/counselingtoolsservice-env-configmap.yaml
> fix: env variables mapping for budibase proxy

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
> fix: env variables for restricted agency admins

- templates/frontend/frontend-env-configmap.yaml
- values.yaml
> feat: added switch for slug fallback

- templates/frontend/frontend-env-configmap.yaml
> feat: enable slug loader default

- templates/migration/templates/migrationservice-deployment.yaml
> fix: image pull policy

- charts/videobackend/templates/prosody/prosody-videoservice-config-configmap.yaml
> fix: prosody script

- templates/messageservice/messageservice-deployment.yaml
- templates/messageservice/messageservice-env-configmap.yaml
> fix: env variables for java 17

- templates/liveservice/liveservice-deployment.yaml
- templates/liveservice/liveservice-env-configmap.yaml
> Tsystems 140

- templates/migration/templates/migrationservice-configmap.yaml
> feat: upgrade migration service to support external dbs

- charts/mariadb/values.yaml
- charts/mongodb/values.yaml
- charts/rabbitmq/values.yaml
> fix: update component versions (mariadb, mongodb, rabbitmq)

- charts/rocketchat/values.yaml
> fix: attempt to upgrade rocketchat

- charts/rabbitmq/templates/rabbitmq-config-configmap.yaml
> fix: remove unneeded variable

- charts/keycloak/templates/keycloak-deployment.yaml
- charts/keycloak/templates/keycloak-env-configmap.yaml
> feat: add java ops append

- templates/agencyservice/agencyservice-deployment.yaml
- templates/agencyservice/agencyservice-env-configmap.yaml
- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-env-configmap.yaml
- templates/liveservice/liveservice-deployment.yaml
- templates/liveservice/liveservice-env-configmap.yaml
- templates/mailservice/mailservice-deployment.yaml
- templates/mailservice/mailservice-env-configmap.yaml
- templates/messageservice/messageservice-deployment.yaml
- templates/messageservice/messageservice-env-configmap.yaml
- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/statisticsservice/statisticsservice-env-configmap.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/uploadservice/uploadservice-env-configmap.yaml
- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
- templates/videoservice/videoservice-deployment.yaml
- templates/videoservice/videoservice-env-configmap.yaml
> feat: add distributed tracing with micrometer and zipkin

- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-env-configmap.yaml
> feat: add sleuth integration with consulting type service

- templates/uploadservice/uploadservice-deployment.yaml
- templates/uploadservice/uploadservice-env-configmap.yaml
> feat: add sleuth integration with upload service

- charts/openldap/templates/openldap-deployment.yaml
> feat: increase limit of ldap files

- templates/consultingtypeservice/consultingtypeservice-env-configmap.yaml
> fix: remove extra space

- templates/consultingtypeservice/consultingtypeservice-env-configmap.yaml
> fix: remove extra spaces

- templates/uploadservice/uploadservice-env-configmap.yaml
> fix: add missing line

- charts/videobackend/values.yaml
> feat: prep jitsi upgrade

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
- templates/userservice/userservice-secret.yaml
- values.yaml
add configs for site24x7
Fixes #
-
-
-
> feat: CARITAS-297-add-site24x7

- templates/userservice/userservice-env-configmap.yaml
> fix: CARITAS-297-add-site24x7

- templates/userservice/userservice-deployment.yaml
- templates/userservice/userservice-env-configmap.yaml
> feat: upgrade userservice to new spring boot

- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/statisticsservice/statisticsservice-env-configmap.yaml
update statisticsservice-deployment.yaml and statisticsservice-env-configmap.yaml
Fixes #
-
-
-
> feat: TSYSTEMS-196

- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/consultingtypeservice/consultingtypeservice-env-configmap.yaml
> feat: upgrade consultingtypeservice to new spring boot

- templates/uploadservice/uploadservice-deployment.yaml
- templates/uploadservice/uploadservice-env-configmap.yaml
> fix: uploadservice deployment

- templates/messageservice/messageservice-deployment.yaml
- templates/messageservice/messageservice-env-configmap.yaml
- values.yaml
> fix: hikari cp configurations

- templates/agencyservice/agencyservice-deployment.yaml
- templates/liveservice/liveservice-deployment.yaml
- templates/mailservice/mailservice-deployment.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/videoservice/videoservice-deployment.yaml
> chore: fix zipkin tracing env variable resolution

- templates/consultingtypeservice/consultingtypeservice-deployment.yaml
- templates/statisticsservice/statisticsservice-deployment.yaml
- templates/uploadservice/uploadservice-deployment.yaml
- templates/userservice/userservice-deployment.yaml
> fix: fix deployments for variable SPRING_ZIPKIN_BASE_URL

- templates/messageservice/messageservice-deployment.yaml
- templates/userservice/userservice-deployment.yaml
add missing SENTRY_PERFORMANCE_MONITORING_ENABLED to userservice-deployment.yaml and messageservice-deployment.yaml files
Fixes #
-
-
-
> fix: DELPHI-232
